graph TD
    subgraph recon_trace Internal Function Flow

        API_calls3["calls/3 (API)"] --> Internal_setup_trace(setup_trace)
        API_calls2["calls/2 (API)"] --> API_calls3

        API_clear["clear/0 (API)"] --> Internal_stop_trace(stop_trace)

        API_format["format/1 (API)"] --> Internal_do_format(do_format)
        API_format_output1["format_trace_output/1 (API)"] --> Internal_do_format_output(do_format_output)
        API_format_output2["format_trace_output/2 (API)"] --> Internal_do_format_output

        %% Internal Logic Functions
        Internal_setup_trace --> Internal_validate_args(validate_args)
        Internal_setup_trace --> Internal_start_tracer(start_tracer_process)
        Internal_setup_trace --> Internal_start_formatter(start_formatter_process)
        Internal_setup_trace --> Erlang_trace_pattern["erlang:trace_pattern/3"]
        Internal_setup_trace --> Erlang_trace["erlang:trace/3"]

        Internal_start_tracer --> TracerLoop(tracer_loop)
        Internal_start_formatter --> FormatterLoop(formatter_loop)

        TracerLoop -- receives trace --> Internal_check_limits(check_limits)
        TracerLoop -- forwards trace --> FormatterLoop
        TracerLoop -- calls --> RL["recon_lib (utils)"]


        FormatterLoop -- receives trace --> Internal_do_format
        Internal_do_format --> Internal_do_format_output
        Internal_do_format_output -- uses --> RR["recon_rec:format/1"]

        Internal_stop_trace --> Internal_stop_process(stop_process: Tracer)
        Internal_stop_trace --> Internal_stop_process(stop_process: Formatter)
        Internal_stop_trace --> Erlang_trace["erlang:trace/3"] 

    end

    %% Styling
    classDef api fill:#BD93F9,stroke:#333,stroke-width:2px,color:#fff;
    classDef internal fill:#f8f8f2,stroke:#50FA7B,stroke-width:1px,color:#282a36;
    classDef external fill:#FF79C6,stroke:#333,stroke-width:1px;
    classDef lib fill:#F1FA8C,stroke:#333,stroke-width:1px;
    classDef rec fill:#FFB86C,stroke:#333,stroke-width:1px;

    class API_calls3,API_calls2,API_clear,API_format,API_format_output1,API_format_output2 api;
    class Internal_setup_trace,Internal_validate_args,Internal_start_tracer,Internal_start_formatter,TracerLoop,FormatterLoop,Internal_check_limits,Internal_do_format,Internal_do_format_output,Internal_stop_trace,Internal_stop_process internal;
    class Erlang_trace_pattern,Erlang_trace external;
    class RL lib;
    class RR rec;
